program gen_time

!       generate a file with the time as data for regressions against time

    implicit none
    integer :: yr,yrbegin,yrend,i,nperyear
    character(80) :: line

    if ( command_argument_count() /= 3 ) then
        print *,'usage: gen_time yrbegin yrend nperyear'
        stop
    endif
    call get_command_argument(1,line)
    read(line,*) yrbegin
    call get_command_argument(2,line)
    read(line,*) yrend
    call get_command_argument(3,line)
    read(line,*) nperyear

    print '(a)','# Time file generated by gen_time'
    print '(a)','# time [yr]'
    do yr=yrbegin,yrend
        print '(i5,366f11.4)',yr,(yr-2000+(i-.5)/nperyear,i=1 ,nperyear)
    enddo

end program gen_time
