# FFLAGS = -g -m64 -Dlinux -fbounds-check -fbackslash -ffpe-trap=invalid,zero,overflow #-fsecond-underscore
FFLAGS = -O3 -m64 -Dlinux -fbackslash -ffpe-trap=invalid,zero,overflow # -fno-backtrace

CFLAGS = -O -m64

FC = gfortran
LD = $(FC) $(FFLAGS) -Wl,-framework -Wl,Accelerate
SYSLIBS=-L/sw/lib -lnetcdff -lnetcdf

RANLIB = ranlib

include ../Makefile.common
