FFLAGS = -Ktrap=fp -g -C -Wl,-Bstatic
# FFLAGS = -Ktrap=fp -fast # -Mvect=sse slows down correlatefield..
EOFFLAGS = $(FFLAGS)

SYSLIBS = -llapack -lblas
FC = f77
LD = f77
RANLIB = echo ready with

LDBIGFLAG = -Wl,-Bstatic

include ../Makefile.common
