# FFLAGS = -Ktrap=fp -g -C
FFLAGS = -Ktrap=fp -O3  -Mlarge_arrays
EOFFLAGS = $(FFLAGS)

CFLAGS = -O2

SYSLIBS = -L$(HOME)/lib -lnetcdff -lnetcdf -lhdf5 -llapack -lblas -lcurl
FC = pgf90
LD = pgf90
RANLIB = echo ready with

###LDBIGFLAG = -Wl,-Bstatic

EXTRAOBJS = getppid.o ieee_is_finite.o

include ../Makefile.common
